apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rw5s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rw5s
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rw5s
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rw5s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rw5s
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dzaw-tenant/rhtap-demo-app/hacbs-test-project-rw5s@sha256:01dec8afff23e62c2cc03e5c6c21e3c07fc94d2e19345744beb78da142309677
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
